// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package weles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// JobFilterAndSort Data for filtering and sorting Weles Jobs lists.
// swagger:model JobFilterAndSort
type JobFilterAndSort struct {

	// job filter
	JobFilter *JobFilter `json:"JobFilter,omitempty"`

	// job sorter
	JobSorter *JobSorter `json:"JobSorter,omitempty"`
}

// Validate validates this job filter and sort
func (m *JobFilterAndSort) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJobFilter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJobSorter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobFilterAndSort) validateJobFilter(formats strfmt.Registry) error {

	if swag.IsZero(m.JobFilter) { // not required
		return nil
	}

	if m.JobFilter != nil {
		if err := m.JobFilter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("JobFilter")
			}
			return err
		}
	}

	return nil
}

func (m *JobFilterAndSort) validateJobSorter(formats strfmt.Registry) error {

	if swag.IsZero(m.JobSorter) { // not required
		return nil
	}

	if m.JobSorter != nil {
		if err := m.JobSorter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("JobSorter")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *JobFilterAndSort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobFilterAndSort) UnmarshalBinary(b []byte) error {
	var res JobFilterAndSort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
