// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	weles "github.com/SamsungSLAV/weles"
)

// JobCreatorCreatedCode is the HTTP code returned for type JobCreatorCreated
const JobCreatorCreatedCode int = 201

/*JobCreatorCreated Created

swagger:response jobCreatorCreated
*/
type JobCreatorCreated struct {

	/*
	  In: Body
	*/
	Payload weles.JobID `json:"body,omitempty"`
}

// NewJobCreatorCreated creates JobCreatorCreated with default headers values
func NewJobCreatorCreated() *JobCreatorCreated {

	return &JobCreatorCreated{}
}

// WithPayload adds the payload to the job creator created response
func (o *JobCreatorCreated) WithPayload(payload weles.JobID) *JobCreatorCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the job creator created response
func (o *JobCreatorCreated) SetPayload(payload weles.JobID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *JobCreatorCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// JobCreatorUnsupportedMediaTypeCode is the HTTP code returned for type JobCreatorUnsupportedMediaType
const JobCreatorUnsupportedMediaTypeCode int = 415

/*JobCreatorUnsupportedMediaType Unsupported media type

swagger:response jobCreatorUnsupportedMediaType
*/
type JobCreatorUnsupportedMediaType struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewJobCreatorUnsupportedMediaType creates JobCreatorUnsupportedMediaType with default headers values
func NewJobCreatorUnsupportedMediaType() *JobCreatorUnsupportedMediaType {

	return &JobCreatorUnsupportedMediaType{}
}

// WithPayload adds the payload to the job creator unsupported media type response
func (o *JobCreatorUnsupportedMediaType) WithPayload(payload *weles.ErrResponse) *JobCreatorUnsupportedMediaType {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the job creator unsupported media type response
func (o *JobCreatorUnsupportedMediaType) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *JobCreatorUnsupportedMediaType) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(415)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// JobCreatorUnprocessableEntityCode is the HTTP code returned for type JobCreatorUnprocessableEntity
const JobCreatorUnprocessableEntityCode int = 422

/*JobCreatorUnprocessableEntity Unprocessable entity

swagger:response jobCreatorUnprocessableEntity
*/
type JobCreatorUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewJobCreatorUnprocessableEntity creates JobCreatorUnprocessableEntity with default headers values
func NewJobCreatorUnprocessableEntity() *JobCreatorUnprocessableEntity {

	return &JobCreatorUnprocessableEntity{}
}

// WithPayload adds the payload to the job creator unprocessable entity response
func (o *JobCreatorUnprocessableEntity) WithPayload(payload *weles.ErrResponse) *JobCreatorUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the job creator unprocessable entity response
func (o *JobCreatorUnprocessableEntity) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *JobCreatorUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// JobCreatorInternalServerErrorCode is the HTTP code returned for type JobCreatorInternalServerError
const JobCreatorInternalServerErrorCode int = 500

/*JobCreatorInternalServerError Internal Server error

swagger:response jobCreatorInternalServerError
*/
type JobCreatorInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewJobCreatorInternalServerError creates JobCreatorInternalServerError with default headers values
func NewJobCreatorInternalServerError() *JobCreatorInternalServerError {

	return &JobCreatorInternalServerError{}
}

// WithPayload adds the payload to the job creator internal server error response
func (o *JobCreatorInternalServerError) WithPayload(payload *weles.ErrResponse) *JobCreatorInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the job creator internal server error response
func (o *JobCreatorInternalServerError) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *JobCreatorInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
