// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	weles "github.com/SamsungSLAV/weles"
)

// JobCancelerNoContentCode is the HTTP code returned for type JobCancelerNoContent
const JobCancelerNoContentCode int = 204

/*JobCancelerNoContent No Content

swagger:response jobCancelerNoContent
*/
type JobCancelerNoContent struct {
}

// NewJobCancelerNoContent creates JobCancelerNoContent with default headers values
func NewJobCancelerNoContent() *JobCancelerNoContent {

	return &JobCancelerNoContent{}
}

// WriteResponse to the client
func (o *JobCancelerNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// JobCancelerForbiddenCode is the HTTP code returned for type JobCancelerForbidden
const JobCancelerForbiddenCode int = 403

/*JobCancelerForbidden Forbidden

swagger:response jobCancelerForbidden
*/
type JobCancelerForbidden struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewJobCancelerForbidden creates JobCancelerForbidden with default headers values
func NewJobCancelerForbidden() *JobCancelerForbidden {

	return &JobCancelerForbidden{}
}

// WithPayload adds the payload to the job canceler forbidden response
func (o *JobCancelerForbidden) WithPayload(payload *weles.ErrResponse) *JobCancelerForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the job canceler forbidden response
func (o *JobCancelerForbidden) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *JobCancelerForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// JobCancelerNotFoundCode is the HTTP code returned for type JobCancelerNotFound
const JobCancelerNotFoundCode int = 404

/*JobCancelerNotFound Not Found

swagger:response jobCancelerNotFound
*/
type JobCancelerNotFound struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewJobCancelerNotFound creates JobCancelerNotFound with default headers values
func NewJobCancelerNotFound() *JobCancelerNotFound {

	return &JobCancelerNotFound{}
}

// WithPayload adds the payload to the job canceler not found response
func (o *JobCancelerNotFound) WithPayload(payload *weles.ErrResponse) *JobCancelerNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the job canceler not found response
func (o *JobCancelerNotFound) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *JobCancelerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// JobCancelerInternalServerErrorCode is the HTTP code returned for type JobCancelerInternalServerError
const JobCancelerInternalServerErrorCode int = 500

/*JobCancelerInternalServerError Internal Server error

swagger:response jobCancelerInternalServerError
*/
type JobCancelerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewJobCancelerInternalServerError creates JobCancelerInternalServerError with default headers values
func NewJobCancelerInternalServerError() *JobCancelerInternalServerError {

	return &JobCancelerInternalServerError{}
}

// WithPayload adds the payload to the job canceler internal server error response
func (o *JobCancelerInternalServerError) WithPayload(payload *weles.ErrResponse) *JobCancelerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the job canceler internal server error response
func (o *JobCancelerInternalServerError) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *JobCancelerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
