// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package artifacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewArtifactListerParams creates a new ArtifactListerParams object
// with the default values initialized.
func NewArtifactListerParams() *ArtifactListerParams {
	var ()
	return &ArtifactListerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewArtifactListerParamsWithTimeout creates a new ArtifactListerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewArtifactListerParamsWithTimeout(timeout time.Duration) *ArtifactListerParams {
	var ()
	return &ArtifactListerParams{

		timeout: timeout,
	}
}

// NewArtifactListerParamsWithContext creates a new ArtifactListerParams object
// with the default values initialized, and the ability to set a context for a request
func NewArtifactListerParamsWithContext(ctx context.Context) *ArtifactListerParams {
	var ()
	return &ArtifactListerParams{

		Context: ctx,
	}
}

// NewArtifactListerParamsWithHTTPClient creates a new ArtifactListerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewArtifactListerParamsWithHTTPClient(client *http.Client) *ArtifactListerParams {
	var ()
	return &ArtifactListerParams{
		HTTPClient: client,
	}
}

/*ArtifactListerParams contains all the parameters to send to the API endpoint
for the artifact lister operation typically these are written to a http.Request
*/
type ArtifactListerParams struct {

	/*After
	  ID of the last element from previous page.

	*/
	After *int64
	/*ArtifactFilterAndSort
	  Artifact Filter and Sort object.

	*/
	ArtifactFilterAndSort ArtifactListerBody
	/*Before
	  ID of first element from next page.

	*/
	Before *int64
	/*Limit
	  Custom page limit. Denotes number of ArtifactInfo structures that will be returned.

	*/
	Limit *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the artifact lister params
func (o *ArtifactListerParams) WithTimeout(timeout time.Duration) *ArtifactListerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the artifact lister params
func (o *ArtifactListerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the artifact lister params
func (o *ArtifactListerParams) WithContext(ctx context.Context) *ArtifactListerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the artifact lister params
func (o *ArtifactListerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the artifact lister params
func (o *ArtifactListerParams) WithHTTPClient(client *http.Client) *ArtifactListerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the artifact lister params
func (o *ArtifactListerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAfter adds the after to the artifact lister params
func (o *ArtifactListerParams) WithAfter(after *int64) *ArtifactListerParams {
	o.SetAfter(after)
	return o
}

// SetAfter adds the after to the artifact lister params
func (o *ArtifactListerParams) SetAfter(after *int64) {
	o.After = after
}

// WithArtifactFilterAndSort adds the artifactFilterAndSort to the artifact lister params
func (o *ArtifactListerParams) WithArtifactFilterAndSort(artifactFilterAndSort ArtifactListerBody) *ArtifactListerParams {
	o.SetArtifactFilterAndSort(artifactFilterAndSort)
	return o
}

// SetArtifactFilterAndSort adds the artifactFilterAndSort to the artifact lister params
func (o *ArtifactListerParams) SetArtifactFilterAndSort(artifactFilterAndSort ArtifactListerBody) {
	o.ArtifactFilterAndSort = artifactFilterAndSort
}

// WithBefore adds the before to the artifact lister params
func (o *ArtifactListerParams) WithBefore(before *int64) *ArtifactListerParams {
	o.SetBefore(before)
	return o
}

// SetBefore adds the before to the artifact lister params
func (o *ArtifactListerParams) SetBefore(before *int64) {
	o.Before = before
}

// WithLimit adds the limit to the artifact lister params
func (o *ArtifactListerParams) WithLimit(limit *int32) *ArtifactListerParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the artifact lister params
func (o *ArtifactListerParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WriteToRequest writes these params to a swagger request
func (o *ArtifactListerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.After != nil {

		// query param after
		var qrAfter int64
		if o.After != nil {
			qrAfter = *o.After
		}
		qAfter := swag.FormatInt64(qrAfter)
		if qAfter != "" {
			if err := r.SetQueryParam("after", qAfter); err != nil {
				return err
			}
		}

	}

	if err := r.SetBodyParam(o.ArtifactFilterAndSort); err != nil {
		return err
	}

	if o.Before != nil {

		// query param before
		var qrBefore int64
		if o.Before != nil {
			qrBefore = *o.Before
		}
		qBefore := swag.FormatInt64(qrBefore)
		if qBefore != "" {
			if err := r.SetQueryParam("before", qBefore); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
