// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

/*
Package server Weles
This is an instance of Weles. [More about this instance of
Weles.](http://weles.yourdomain.com).

Terms Of Service:

http://weles.yourdomain.com/terms/


    Schemes:
      http
    Host: localhost:5010
    BasePath: /api/v1
    Version: v1
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <admin@yourdomain.com>

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package server
