// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	weles "github.com/SamsungSLAV/weles"
)

// JobCreatorReader is a Reader for the JobCreator structure.
type JobCreatorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobCreatorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewJobCreatorCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 415:
		result := NewJobCreatorUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewJobCreatorUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewJobCreatorInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJobCreatorCreated creates a JobCreatorCreated with default headers values
func NewJobCreatorCreated() *JobCreatorCreated {
	return &JobCreatorCreated{}
}

/*JobCreatorCreated handles this case with default header values.

Created
*/
type JobCreatorCreated struct {
	Payload weles.JobID
}

func (o *JobCreatorCreated) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] jobCreatorCreated  %+v", 201, o.Payload)
}

func (o *JobCreatorCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJobCreatorUnsupportedMediaType creates a JobCreatorUnsupportedMediaType with default headers values
func NewJobCreatorUnsupportedMediaType() *JobCreatorUnsupportedMediaType {
	return &JobCreatorUnsupportedMediaType{}
}

/*JobCreatorUnsupportedMediaType handles this case with default header values.

Unsupported media type
*/
type JobCreatorUnsupportedMediaType struct {
	Payload *weles.ErrResponse
}

func (o *JobCreatorUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] jobCreatorUnsupportedMediaType  %+v", 415, o.Payload)
}

func (o *JobCreatorUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(weles.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJobCreatorUnprocessableEntity creates a JobCreatorUnprocessableEntity with default headers values
func NewJobCreatorUnprocessableEntity() *JobCreatorUnprocessableEntity {
	return &JobCreatorUnprocessableEntity{}
}

/*JobCreatorUnprocessableEntity handles this case with default header values.

Unprocessable entity
*/
type JobCreatorUnprocessableEntity struct {
	Payload *weles.ErrResponse
}

func (o *JobCreatorUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] jobCreatorUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *JobCreatorUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(weles.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJobCreatorInternalServerError creates a JobCreatorInternalServerError with default headers values
func NewJobCreatorInternalServerError() *JobCreatorInternalServerError {
	return &JobCreatorInternalServerError{}
}

/*JobCreatorInternalServerError handles this case with default header values.

Internal Server error
*/
type JobCreatorInternalServerError struct {
	Payload *weles.ErrResponse
}

func (o *JobCreatorInternalServerError) Error() string {
	return fmt.Sprintf("[POST /jobs][%d] jobCreatorInternalServerError  %+v", 500, o.Payload)
}

func (o *JobCreatorInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(weles.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
