// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewJobCreatorParams creates a new JobCreatorParams object
// with the default values initialized.
func NewJobCreatorParams() *JobCreatorParams {
	var ()
	return &JobCreatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJobCreatorParamsWithTimeout creates a new JobCreatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJobCreatorParamsWithTimeout(timeout time.Duration) *JobCreatorParams {
	var ()
	return &JobCreatorParams{

		timeout: timeout,
	}
}

// NewJobCreatorParamsWithContext creates a new JobCreatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewJobCreatorParamsWithContext(ctx context.Context) *JobCreatorParams {
	var ()
	return &JobCreatorParams{

		Context: ctx,
	}
}

// NewJobCreatorParamsWithHTTPClient creates a new JobCreatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJobCreatorParamsWithHTTPClient(client *http.Client) *JobCreatorParams {
	var ()
	return &JobCreatorParams{
		HTTPClient: client,
	}
}

/*JobCreatorParams contains all the parameters to send to the API endpoint
for the job creator operation typically these are written to a http.Request
*/
type JobCreatorParams struct {

	/*Yamlfile
	  is Job description yaml file.

	*/
	Yamlfile runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the job creator params
func (o *JobCreatorParams) WithTimeout(timeout time.Duration) *JobCreatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the job creator params
func (o *JobCreatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the job creator params
func (o *JobCreatorParams) WithContext(ctx context.Context) *JobCreatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the job creator params
func (o *JobCreatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the job creator params
func (o *JobCreatorParams) WithHTTPClient(client *http.Client) *JobCreatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the job creator params
func (o *JobCreatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithYamlfile adds the yamlfile to the job creator params
func (o *JobCreatorParams) WithYamlfile(yamlfile runtime.NamedReadCloser) *JobCreatorParams {
	o.SetYamlfile(yamlfile)
	return o
}

// SetYamlfile adds the yamlfile to the job creator params
func (o *JobCreatorParams) SetYamlfile(yamlfile runtime.NamedReadCloser) {
	o.Yamlfile = yamlfile
}

// WriteToRequest writes these params to a swagger request
func (o *JobCreatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form file param yamlfile
	if err := r.SetFileParam("yamlfile", o.Yamlfile); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
