// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewJobCancelerParams creates a new JobCancelerParams object
// with the default values initialized.
func NewJobCancelerParams() *JobCancelerParams {
	var ()
	return &JobCancelerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJobCancelerParamsWithTimeout creates a new JobCancelerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJobCancelerParamsWithTimeout(timeout time.Duration) *JobCancelerParams {
	var ()
	return &JobCancelerParams{

		timeout: timeout,
	}
}

// NewJobCancelerParamsWithContext creates a new JobCancelerParams object
// with the default values initialized, and the ability to set a context for a request
func NewJobCancelerParamsWithContext(ctx context.Context) *JobCancelerParams {
	var ()
	return &JobCancelerParams{

		Context: ctx,
	}
}

// NewJobCancelerParamsWithHTTPClient creates a new JobCancelerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJobCancelerParamsWithHTTPClient(client *http.Client) *JobCancelerParams {
	var ()
	return &JobCancelerParams{
		HTTPClient: client,
	}
}

/*JobCancelerParams contains all the parameters to send to the API endpoint
for the job canceler operation typically these are written to a http.Request
*/
type JobCancelerParams struct {

	/*JobID*/
	JobID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the job canceler params
func (o *JobCancelerParams) WithTimeout(timeout time.Duration) *JobCancelerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the job canceler params
func (o *JobCancelerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the job canceler params
func (o *JobCancelerParams) WithContext(ctx context.Context) *JobCancelerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the job canceler params
func (o *JobCancelerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the job canceler params
func (o *JobCancelerParams) WithHTTPClient(client *http.Client) *JobCancelerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the job canceler params
func (o *JobCancelerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJobID adds the jobID to the job canceler params
func (o *JobCancelerParams) WithJobID(jobID uint64) *JobCancelerParams {
	o.SetJobID(jobID)
	return o
}

// SetJobID adds the jobId to the job canceler params
func (o *JobCancelerParams) SetJobID(jobID uint64) {
	o.JobID = jobID
}

// WriteToRequest writes these params to a swagger request
func (o *JobCancelerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param JobID
	if err := r.SetPathParam("JobID", swag.FormatUint64(o.JobID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
