// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package artifacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ArtifactDownloaderHandlerFunc turns a function with the right signature into a artifact downloader handler
type ArtifactDownloaderHandlerFunc func(ArtifactDownloaderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ArtifactDownloaderHandlerFunc) Handle(params ArtifactDownloaderParams) middleware.Responder {
	return fn(params)
}

// ArtifactDownloaderHandler interface for that can handle valid artifact downloader params
type ArtifactDownloaderHandler interface {
	Handle(ArtifactDownloaderParams) middleware.Responder
}

// NewArtifactDownloader creates a new http.Handler for the artifact downloader operation
func NewArtifactDownloader(ctx *middleware.Context, handler ArtifactDownloaderHandler) *ArtifactDownloader {
	return &ArtifactDownloader{Context: ctx, Handler: handler}
}

/*ArtifactDownloader swagger:route GET /artifacts/{ArtifactID} artifacts artifactDownloader

Download artifact.

ArtifactDownloader returns requested artifact.

*/
type ArtifactDownloader struct {
	Context *middleware.Context
	Handler ArtifactDownloaderHandler
}

func (o *ArtifactDownloader) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewArtifactDownloaderParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
