// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package artifacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ArtifactListerHandlerFunc turns a function with the right signature into a artifact lister handler
type ArtifactListerHandlerFunc func(ArtifactListerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ArtifactListerHandlerFunc) Handle(params ArtifactListerParams) middleware.Responder {
	return fn(params)
}

// ArtifactListerHandler interface for that can handle valid artifact lister params
type ArtifactListerHandler interface {
	Handle(ArtifactListerParams) middleware.Responder
}

// NewArtifactLister creates a new http.Handler for the artifact lister operation
func NewArtifactLister(ctx *middleware.Context, handler ArtifactListerHandler) *ArtifactLister {
	return &ArtifactLister{Context: ctx, Handler: handler}
}

/*ArtifactLister swagger:route POST /artifacts/list artifacts artifactLister

List artifacts with filter and sort features

ArtifactLister returns information on filtered Weles artifacts.

*/
type ArtifactLister struct {
	Context *middleware.Context
	Handler ArtifactListerHandler
}

func (o *ArtifactLister) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewArtifactListerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
