// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package artifacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	weles "github.com/SamsungSLAV/weles"
)

// ArtifactDownloaderOKCode is the HTTP code returned for type ArtifactDownloaderOK
const ArtifactDownloaderOKCode int = 200

/*ArtifactDownloaderOK OK

swagger:response artifactDownloaderOK
*/
type ArtifactDownloaderOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewArtifactDownloaderOK creates ArtifactDownloaderOK with default headers values
func NewArtifactDownloaderOK() *ArtifactDownloaderOK {

	return &ArtifactDownloaderOK{}
}

// WithPayload adds the payload to the artifact downloader o k response
func (o *ArtifactDownloaderOK) WithPayload(payload io.ReadCloser) *ArtifactDownloaderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the artifact downloader o k response
func (o *ArtifactDownloaderOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ArtifactDownloaderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ArtifactDownloaderBadRequestCode is the HTTP code returned for type ArtifactDownloaderBadRequest
const ArtifactDownloaderBadRequestCode int = 400

/*ArtifactDownloaderBadRequest Bad Request

swagger:response artifactDownloaderBadRequest
*/
type ArtifactDownloaderBadRequest struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewArtifactDownloaderBadRequest creates ArtifactDownloaderBadRequest with default headers values
func NewArtifactDownloaderBadRequest() *ArtifactDownloaderBadRequest {

	return &ArtifactDownloaderBadRequest{}
}

// WithPayload adds the payload to the artifact downloader bad request response
func (o *ArtifactDownloaderBadRequest) WithPayload(payload *weles.ErrResponse) *ArtifactDownloaderBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the artifact downloader bad request response
func (o *ArtifactDownloaderBadRequest) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ArtifactDownloaderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ArtifactDownloaderNotFoundCode is the HTTP code returned for type ArtifactDownloaderNotFound
const ArtifactDownloaderNotFoundCode int = 404

/*ArtifactDownloaderNotFound Not Found

swagger:response artifactDownloaderNotFound
*/
type ArtifactDownloaderNotFound struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewArtifactDownloaderNotFound creates ArtifactDownloaderNotFound with default headers values
func NewArtifactDownloaderNotFound() *ArtifactDownloaderNotFound {

	return &ArtifactDownloaderNotFound{}
}

// WithPayload adds the payload to the artifact downloader not found response
func (o *ArtifactDownloaderNotFound) WithPayload(payload *weles.ErrResponse) *ArtifactDownloaderNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the artifact downloader not found response
func (o *ArtifactDownloaderNotFound) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ArtifactDownloaderNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ArtifactDownloaderInternalServerErrorCode is the HTTP code returned for type ArtifactDownloaderInternalServerError
const ArtifactDownloaderInternalServerErrorCode int = 500

/*ArtifactDownloaderInternalServerError Internal Server error

swagger:response artifactDownloaderInternalServerError
*/
type ArtifactDownloaderInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewArtifactDownloaderInternalServerError creates ArtifactDownloaderInternalServerError with default headers values
func NewArtifactDownloaderInternalServerError() *ArtifactDownloaderInternalServerError {

	return &ArtifactDownloaderInternalServerError{}
}

// WithPayload adds the payload to the artifact downloader internal server error response
func (o *ArtifactDownloaderInternalServerError) WithPayload(payload *weles.ErrResponse) *ArtifactDownloaderInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the artifact downloader internal server error response
func (o *ArtifactDownloaderInternalServerError) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ArtifactDownloaderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
