// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package artifacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	weles "github.com/SamsungSLAV/weles"
)

// ArtifactDownloadOKCode is the HTTP code returned for type ArtifactDownloadOK
const ArtifactDownloadOKCode int = 200

/*ArtifactDownloadOK OK

swagger:response artifactDownloadOK
*/
type ArtifactDownloadOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewArtifactDownloadOK creates ArtifactDownloadOK with default headers values
func NewArtifactDownloadOK() *ArtifactDownloadOK {

	return &ArtifactDownloadOK{}
}

// WithPayload adds the payload to the artifact download o k response
func (o *ArtifactDownloadOK) WithPayload(payload io.ReadCloser) *ArtifactDownloadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the artifact download o k response
func (o *ArtifactDownloadOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ArtifactDownloadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ArtifactDownloadBadRequestCode is the HTTP code returned for type ArtifactDownloadBadRequest
const ArtifactDownloadBadRequestCode int = 400

/*ArtifactDownloadBadRequest Bad Request

swagger:response artifactDownloadBadRequest
*/
type ArtifactDownloadBadRequest struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewArtifactDownloadBadRequest creates ArtifactDownloadBadRequest with default headers values
func NewArtifactDownloadBadRequest() *ArtifactDownloadBadRequest {

	return &ArtifactDownloadBadRequest{}
}

// WithPayload adds the payload to the artifact download bad request response
func (o *ArtifactDownloadBadRequest) WithPayload(payload *weles.ErrResponse) *ArtifactDownloadBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the artifact download bad request response
func (o *ArtifactDownloadBadRequest) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ArtifactDownloadBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ArtifactDownloadNotFoundCode is the HTTP code returned for type ArtifactDownloadNotFound
const ArtifactDownloadNotFoundCode int = 404

/*ArtifactDownloadNotFound Not Found

swagger:response artifactDownloadNotFound
*/
type ArtifactDownloadNotFound struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewArtifactDownloadNotFound creates ArtifactDownloadNotFound with default headers values
func NewArtifactDownloadNotFound() *ArtifactDownloadNotFound {

	return &ArtifactDownloadNotFound{}
}

// WithPayload adds the payload to the artifact download not found response
func (o *ArtifactDownloadNotFound) WithPayload(payload *weles.ErrResponse) *ArtifactDownloadNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the artifact download not found response
func (o *ArtifactDownloadNotFound) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ArtifactDownloadNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ArtifactDownloadInternalServerErrorCode is the HTTP code returned for type ArtifactDownloadInternalServerError
const ArtifactDownloadInternalServerErrorCode int = 500

/*ArtifactDownloadInternalServerError Internal Server error

swagger:response artifactDownloadInternalServerError
*/
type ArtifactDownloadInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *weles.ErrResponse `json:"body,omitempty"`
}

// NewArtifactDownloadInternalServerError creates ArtifactDownloadInternalServerError with default headers values
func NewArtifactDownloadInternalServerError() *ArtifactDownloadInternalServerError {

	return &ArtifactDownloadInternalServerError{}
}

// WithPayload adds the payload to the artifact download internal server error response
func (o *ArtifactDownloadInternalServerError) WithPayload(payload *weles.ErrResponse) *ArtifactDownloadInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the artifact download internal server error response
func (o *ArtifactDownloadInternalServerError) SetPayload(payload *weles.ErrResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ArtifactDownloadInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
