// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2017-2018 Samsung Electronics Co., Ltd All Rights Reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License
//

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// VersionHandlerFunc turns a function with the right signature into a version handler
type VersionHandlerFunc func(VersionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VersionHandlerFunc) Handle(params VersionParams) middleware.Responder {
	return fn(params)
}

// VersionHandler interface for that can handle valid version params
type VersionHandler interface {
	Handle(VersionParams) middleware.Responder
}

// NewVersion creates a new http.Handler for the version operation
func NewVersion(ctx *middleware.Context, handler VersionHandler) *Version {
	return &Version{Context: ctx, Handler: handler}
}

/*Version swagger:route GET /version general version

Show current version of Weles internals

Version and state of API (e.g. v1 obsolete, v2 stable, v3 devel) and
server version.

*/
type Version struct {
	Context *middleware.Context
	Handler VersionHandler
}

func (o *Version) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewVersionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
